/*
# Create cvs table for CVoice

1. New Tables
- `cvs`
- `id` (uuid, primary key) — unique identifier for each CV
- `user_id` (uuid, nullable, references auth.users) — the owner of the CV
- `answers` (jsonb) — the full answers object from the interview { question_key: answer }
- `name` (text) — extracted candidate name
- `target_role` (text) — the role the candidate is seeking
- `recent_role` (text) — most recent job title
- `recent_company` (text) — most recent company
- `recent_duties` (text) — day-to-day description
- `recent_achievement` (text) — key achievement
- `previous_role` (text) — prior role description
- `skills` (text[]) — array of skills
- `education` (text) — education description
- `extras` (text) — extra info (courses, certs, etc.)
- `target_next` (text) — what the candidate wants next
- `share_token` (uuid, unique) — public sharing token for /cv/share/:token
- `created_at` (timestamptz) — when the CV was created

2. Security
- Enable RLS on `cvs`.
- Owner-scoped CRUD: each authenticated user can only access rows they own.
- Public read by share_token: anyone can view a CV by its share token.
- The `user_id` column is nullable (edge function inserts with service role key).

3. Notes
- The share_token is a UUID generated by the edge function.
- The edge function inserts with the service role key, bypassing RLS.
- `current_role` is a reserved word in PostgreSQL, so `recent_role` / `recent_company` are used instead.
*/

CREATE TABLE IF NOT EXISTS cvs (
  id uuid PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  name text NOT NULL DEFAULT '',
  target_role text NOT NULL DEFAULT '',
  recent_role text NOT NULL DEFAULT '',
  recent_company text NOT NULL DEFAULT '',
  recent_duties text NOT NULL DEFAULT '',
  recent_achievement text NOT NULL DEFAULT '',
  previous_role text NOT NULL DEFAULT '',
  skills text[] NOT NULL DEFAULT '{}',
  education text NOT NULL DEFAULT '',
  extras text NOT NULL DEFAULT '',
  target_next text NOT NULL DEFAULT '',
  share_token uuid UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE cvs ENABLE ROW LEVEL SECURITY;

-- Owner-scoped policies: authenticated users can CRUD their own CVs
DROP POLICY IF EXISTS "select_own_cvs" ON cvs;
CREATE POLICY "select_own_cvs" ON cvs FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_cvs" ON cvs;
CREATE POLICY "insert_own_cvs" ON cvs FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_cvs" ON cvs;
CREATE POLICY "update_own_cvs" ON cvs FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_cvs" ON cvs;
CREATE POLICY "delete_own_cvs" ON cvs FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- Public read by share_token: anyone (including anon) can view a CV by its share token
DROP POLICY IF EXISTS "select_shared_cv" ON cvs;
CREATE POLICY "select_shared_cv" ON cvs FOR SELECT
  TO anon, authenticated USING (share_token IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_cvs_user_id ON cvs(user_id);
CREATE INDEX IF NOT EXISTS idx_cvs_share_token ON cvs(share_token);
